export const DONOR_DETAILS = "DONOR_DETAILS";
export const QUESTIONNAIRE = "QUESTIONNAIRE";
export const ELIGIBILITYASSESSMENT = "ELIGIBILITYASSESSMENT";
export const PAYMENTS = "PAYMENTS";
export const KITSTATUS = "KITSTATUS";
export const UCUNITSTATUS = "UCUNITSTATUS";
export const CERTIFICATE = "CERTIFICATE";
export const INPUT_TYPE_YESANDNO = "YESANDNO";
export const INPUT_TYPE_CHECKBOX = "CHECKBOX";
export const INPUT_TYPE_MULTIPLE_CHECKBOX = "MULTIPLE_CHECKBOX";
export const INPUT_TYPE_TEXT = "TEXT";
export const INPUT_TYPE_DATE = "DATE";
export const QUESTIONNAIRE_ONE = "QUESTIONNAIRE_ONE";
export const QUESTIONNAIRE_TWO = "QUESTIONNAIRE_TWO";
export const EXPECTED_DELIVERY_QUESTION_ONE = "EXPECTED_DELIVERY_QUESTION_ONE";
export const EXPECTED_DELIVERY_QUESTION_TWO = "EXPECTED_DELIVERY_QUESTION_TWO";
export const EXPECTED_DELIVERY_QUESTION_THREE =
  "EXPECTED_DELIVERY_QUESTION_THREE";
export const EXPECTED_DELIVERY_QUESTION_FOUR =
  "EXPECTED_DELIVERY_QUESTION_FOUR";
export const EXPECTED_DELIVERY_QUESTION_FIVE =
  "EXPECTED_DELIVERY_QUESTION_FIVE";
export const EXPECTED_DELIVERY_QUESTION_SIX = "EXPECTED_DELIVERY_QUESTION_SIX";
